language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t roy1729/docker-react -f Dockerfile.dev .

script:
    - docker run roy1729/docker-react npm run test -- --coverage
